### ISSUE TITLE
I raise to took an error what was i to do

### ISSUE THREAD

**Issue by aibtiy** [sergius02/Sherlock#15]
Hello, i got the message the bellow of the command ("ninja")

Here the print output what bas become for that

`Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Downloads/github.com/sergius02/Sherlock/meson/post_install.py", line 15, in <module>
    subprocess.call(['update-desktop-database', '-q', desktop_database_dir])
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'update-desktop-database': 'update-desktop-database'
Failed to run install script '/mnt/c/Users/Administrator/Downloads/github.com/sergius02/Sherlock/meson/post_install.py'
FAILED: meson-install
/usr/bin/python3 /usr/bin/meson --internal install /mnt/c/Users/Administrator/Downloads/github.com/sergius02/Sherlock/build/meson-private/install.dat
ninja: build stopped: subcommand failed.`

The message from output printed are has installed what are needed from that and that running through on windows substem linux of the ubuntu os.

Thank you for any message under had to solving

**Comment by sergius02** [comment]
Hi!, i have update the code in https://github.com/sergius02/Sherlock/commit/29910e41f4a176bfc2f48e5fba2a06153f35557e 

I think the problem is because the post_instal script is trying to update some desktop things, but in WSL there's 'no desktop'. Please try it with the new version
